#!/usr/bin/ksh
#==================================================================================
# Unit tests for fizzbuzz sample in korn
#
#==================================================================================
. ./korn_spec
. ./fizzbuzz-korn

function numbers_divisible_by_5_and_7 {
    for i in 3 6 9 81
    do
       it "returns Fizz for $i"
       fizz_it $i
       expect $fizz_result to_be 'Fizz'
    done
}

function numbers_divisible_by_3 {
    for i in 3 6 9 81
    do
       it "returns Fizz for $i"
       fizz_it $i
       expect $fizz_result to_be 'Fizz'
    done
}

function numbers_divisible_by_5 {
    for i in 5 10 20
    do
       it "returns Buzz for $i"
       fizz_it $i
       expect $fizz_result to_be 'Buzz'
    done
}

function numbers_divisible_by_7 {
    for i in 7 14 28
    do
       it "returns Baz for $i"
       fizz_it $i
       expect $fizz_result to_be 'Baz'
    done
}

function numbers_divisible_by_3_and_5 {
    for i in 15 60 900
    do
       it "returns FizzBuzz for $i"
       fizz_it $i
       expect $fizz_result to_be 'FizzBuzz'
    done
}

function numbers_divisible_by_3_and_7 {
    for i in 21 84 
    do
       it "returns FizzBaz for $i"
       fizz_it $i
       expect $fizz_result to_be 'FizzBaz'
    done
}

function numbers_divisible_by_5_and_7 {
    for i in 35 70 
    do
       it "returns BuzzBaz for $i"
       fizz_it $i
       expect $fizz_result to_be 'BuzzBaz'
    done
}

function numbers_divisible_by_3_and_5_and_7 {
    for i in 105 630
    do
       it "returns FizzBuzzBaz for $i"
       fizz_it $i
       expect $fizz_result to_be 'FizzBuzzBaz'
    done
}

print_header fizzbuzz_korn
numbers_divisible_by_3
numbers_divisible_by_5
numbers_divisible_by_7
numbers_divisible_by_3_and_5
numbers_divisible_by_3_and_7
numbers_divisible_by_5_and_7
numbers_divisible_by_3_and_5_and_7
print_trailer

exit 0